import { auth } from "@clerk/nextjs/server";
import { callBuilderWithFallback } from "@/lib/openrouter-client";
import { checkSyntax } from "@/lib/validator";
import { callGeminiRepair } from "@/lib/gemini-client";

export const runtime = "nodejs";

const BUILDER_SYSTEM_PROMPT = `You are a React + Vite frontend code generator. Generate ONLY the raw
file content with no explanation, no markdown code fences, no triple
backticks, no commentary, no preamble.
Output only the exact file content that should be written to disk.
Rules:
- Use React 18 functional components with hooks only.
- Use Tailwind CSS 3 utility classes for all styling. No CSS-in-JS.
  No styled-components. No inline style objects unless absolutely required.
- All import paths must be relative (e.g. ./components/Hero).
- Do not use require(). Use ES module import/export only.
- Each component file must export a single default function component.
- Keep each file focused and under 120 lines when possible.
- Follow the project's design system exactly: use the specified colors,
  fonts, and visual style consistently across all components.
- Make designs visually impressive: use gradients, proper spacing,
  modern typography, hover effects, and responsive layouts.
- For package.json, always output valid JSON and merge plan dependencies
  into this exact base structure:
  {
    "name": "devflow-project",
    "private": true,
    "version": "0.0.0",
    "type": "module",
    "scripts": { "dev": "vite", "build": "vite build" },
    "dependencies": {
      "react": "^18.2.0",
      "react-dom": "^18.2.0"
    },
    "devDependencies": {
      "vite": "^5.0.0",
      "@vitejs/plugin-react": "^4.0.0",
      "tailwindcss": "^3.4.0",
      "autoprefixer": "^10.4.0",
      "postcss": "^8.4.0"
    }
  }
- For index.html always load the Tailwind CDN as a fallback:
  <script src="https://cdn.tailwindcss.com" crossorigin></script>
- For src/main.jsx always use:
  import React from 'react'
  import ReactDOM from 'react-dom/client'
  import './index.css'
  import App from './App'
  ReactDOM.createRoot(document.getElementById('root')).render(
    <React.StrictMode><App /></React.StrictMode>
  )`;

const getErrorMessage = (err: unknown): string => {
  if (err instanceof Error) return err.message;
  return String(err);
};

export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return new Response("Unauthorized", { status: 401 });
    }

    const { filename, plan, selectedModel, fileIndex } = await req.json();
    if (!filename || !plan) {
      return new Response("Bad Request: Missing filename or plan", { status: 400 });
    }

    const formattedFilename = filename.startsWith("/") ? filename : "/" + filename;
    console.log(`[GENERATE_FILE_ROUTE] File: "${formattedFilename}" (index: ${fileIndex})`);

    // 1. Boilerplate Generation (Synchronous & Instant)
    let fileCode = "";
    let generatedLocally = false;

    if (formattedFilename === "/index.html") {
      fileCode = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${plan.projectTitle || "DevFlow App"}</title>
    <meta name="description" content="${plan.description || "Generated by DevFlow"}" />
    <script src="https://cdn.tailwindcss.com" crossorigin></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`;
      generatedLocally = true;
    } else if (formattedFilename === "/src/index.css") {
      fileCode = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

code {
  font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
    monospace;
}`;
      generatedLocally = true;
    } else if (formattedFilename === "/src/main.jsx" || formattedFilename === "/src/main.js") {
      fileCode = `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`;
      generatedLocally = true;
    } else if (formattedFilename === "/package.json") {
      const cleanName = (plan.projectTitle || "devflow-project")
        .toLowerCase()
        .trim()
        .replace(/\s+/g, "-")
        .replace(/[^a-z0-9-_]/g, "");
      const packageJsonObj = {
        name: cleanName || "devflow-project",
        private: true,
        version: "0.0.0",
        type: "module",
        description: plan.description || "Generated by DevFlow",
        scripts: {
          dev: "vite",
          build: "vite build"
        },
        dependencies: {
          react: "^18.2.0",
          "react-dom": "^18.2.0",
          ...(plan.dependencies || {})
        },
        devDependencies: {
          vite: "^5.0.0",
          "@vitejs/plugin-react": "^4.0.0",
          tailwindcss: "^3.4.0",
          autoprefixer: "^10.4.0",
          postcss: "^8.4.0"
        }
      };
      fileCode = JSON.stringify(packageJsonObj, null, 2);
      generatedLocally = true;
    } else if (formattedFilename === "/vite.config.js") {
      fileCode = `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});`;
      generatedLocally = true;
    } else if (formattedFilename === "/tailwind.config.js") {
      fileCode = `export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};`;
      generatedLocally = true;
    } else if (formattedFilename === "/postcss.config.js") {
      fileCode = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};`;
      generatedLocally = true;
    }

    if (generatedLocally) {
      console.log(`[GENERATE_FILE_ROUTE] Boilerplate generated instantly: "${formattedFilename}"`);
      return Response.json({ filename: formattedFilename, code: fileCode });
    }

    // 2. LLM Generation for dynamic code files
    const isAppFile = formattedFilename.includes("App");
    const componentName = formattedFilename.split("/").pop()?.replace(/\.\w+$/, "") || "";
    const designCtx = plan.designSystem
      ? `\nDesign: style="${plan.designSystem.style}", primary="${plan.designSystem.colors?.primary}", accent="${plan.designSystem.colors?.accent}", bg="${plan.designSystem.colors?.background}", font="${plan.designSystem.fontFamily}"`
      : "";
    const sectionsCtx = plan.sections?.length ? `\nSections in order: ${plan.sections.join(", ")}` : "";

    const userMessage = `Generate the complete content for file: ${formattedFilename}
Project: ${plan.projectTitle} — ${plan.description}${designCtx}${sectionsCtx}
All files: ${(plan.files || []).map((f: string) => f.startsWith("/") ? f : "/" + f).join(", ")}
Dependencies: ${JSON.stringify(plan.dependencies || {})}
${isAppFile
  ? "App.jsx must ONLY import and render the component files in order. Do NOT write any section UI code inline."
  : `This file implements the "${componentName}" section/component.`}
Output only the raw file content. No markdown. No explanation.`;

    const openrouterKeys = [
      process.env.OPENROUTER_API_KEY_1 || "",
      process.env.OPENROUTER_API_KEY_2 || "",
    ].filter(Boolean);

    const selectedKey = openrouterKeys.length > 0
      ? openrouterKeys[(fileIndex ?? 0) % openrouterKeys.length]
      : undefined;

    const fileStartTime = Date.now();
    let result;
    try {
      result = await callBuilderWithFallback(BUILDER_SYSTEM_PROMPT, userMessage, selectedModel, selectedKey);
      const duration = Date.now() - fileStartTime;
      console.log(`[GENERATE_FILE_ROUTE] LLM build complete | Model: ${result.modelUsed} | Duration: ${duration}ms`);
    } catch (err: unknown) {
      console.error(`[GENERATE_FILE_ROUTE] Fallback generation failed for ${formattedFilename}:`, getErrorMessage(err));
      return new Response(
        JSON.stringify({ error: `Generation failed: ${getErrorMessage(err)}` }),
        { status: 500, headers: { "Content-Type": "application/json" } }
      );
    }

    let code = result.content;

    // 3. Syntax Validation & Repair
    let syntaxError = checkSyntax(code, formattedFilename);
    if (syntaxError) {
      console.warn(`[GENERATE_FILE_ROUTE] Syntax error detected in ${formattedFilename}: ${syntaxError}. Repairing...`);
      let repaired = false;
      for (let attempt = 1; attempt <= 2; attempt++) {
        try {
          code = await callGeminiRepair(formattedFilename, syntaxError!, code);
          syntaxError = checkSyntax(code, formattedFilename);
          if (!syntaxError) {
            repaired = true;
            console.log(`[GENERATE_FILE_ROUTE] Repair attempt ${attempt} succeeded!`);
            break;
          }
        } catch (repairErr: unknown) {
          console.error(`[GENERATE_FILE_ROUTE] Repair attempt ${attempt} failed:`, getErrorMessage(repairErr));
        }
      }
      
      if (!repaired) {
        console.warn(`[GENERATE_FILE_ROUTE] Repair failed, returning code with warning.`);
        return Response.json({ filename: formattedFilename, code, warning: "syntax_error" });
      }
    }

    return Response.json({ filename: formattedFilename, code });
  } catch (err: unknown) {
    console.error("[GENERATE_FILE_ROUTE] Route error:", getErrorMessage(err));
    return new Response(
      JSON.stringify({ error: getErrorMessage(err) || "Internal server error" }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}
